In [23]:
import requests
from lxml import html
from bs4 import BeautifulSoup

In [30]:
page=requests.get("http://edulix.com/unisearch/user.php?uid=148513")
tree=html.fromstring(page.content)

soup = BeautifulSoup(page.content, 'html.parser')

In [33]:
allTDs = soup.table.find_all('td')
print allTDs
for i in range(len(allTDs)):
    text = allTDs[i].string
    if text == None:
        text = ""
    print "td", text.strip()

[<td align="center" class="orange_title tdhor" colspan="2" id="sub_title">
                Details of
                <a class="no_uline" href="" style="color:#d73117 !important;">1987frank</a> </td>, <td width="50%">Real Name</td>, <td width="50%">
                franklin            </td>, <td>Edulix Nickname</td>, <td>
                1987frank            </td>, <td class="orange_title tdhor" colspan="2" id="sub_title">Application Details</td>, <td>Program</td>, <td>
                MS            </td>, <td>Major</td>, <td>
                Computer Science            </td>, <td>Specialization</td>, <td>
                Artificial Intelligence,Algorithms,Programming Languages            </td>, <td>Term and Year</td>, <td>
                Spring - 2014            </td>, <td class="orange_title tdhor" colspan="2" id="sub_title">Standardized Test Scores</td>, <td class="tdbottom" colspan="2">
<table border="0" width="100%">
<tr>
<td align="left">GRE</td>
<td align="right">Quantitative:</td>
<td>
                            170                        </td>
<td align="right">Verbal:</td>
<td>
                            153                        </td>
<td align="right">AWA:</td>
<td>
                            3.5                        </td>
</tr>
<tr>
<td align="left">GMAT</td>
<td align="right">Quantitative:</td>
<td>
</td>
<td align="right">Verbal:</td>
<td>
</td>
<td align="right">AWA:</td>
<td>
</td>
<td align="right">Integrated Reasoning:</td>
<td>
</td>
</tr>
<tr>
<td align="left">TOEFL</td>
<td align="right">Score:</td>
<td>
                            105                        </td>
<td align="right">TWE (Essay):</td>
<td>
                            29                        </td>
<td colspan="2"> </td>
</tr>
<tr>
<td align="left">IELTS</td>
<td align="right">Score:</td>
<td>
</td>
</tr>
</table>
</td>, <td align="left">GRE</td>, <td align="right">Quantitative:</td>, <td>
                            170                        </td>, <td align="right">Verbal:</td>, <td>
                            153                        </td>, <td align="right">AWA:</td>, <td>
                            3.5                        </td>, <td align="left">GMAT</td>, <td align="right">Quantitative:</td>, <td>
</td>, <td align="right">Verbal:</td>, <td>
</td>, <td align="right">AWA:</td>, <td>
</td>, <td align="right">Integrated Reasoning:</td>, <td>
</td>, <td align="left">TOEFL</td>, <td align="right">Score:</td>, <td>
                            105                        </td>, <td align="right">TWE (Essay):</td>, <td>
                            29                        </td>, <td colspan="2"> </td>, <td align="left">IELTS</td>, <td align="right">Score:</td>, <td>
</td>, <td class="orange_title tdhor" colspan="2" id="sub_title">Undergraduate Details</td>, <td>University/College</td>, <td>
                College Of Engineering, Trivandrum            </td>, <td>Department</td>, <td>
                CSE            </td>, <td>Grade</td>, <td>
                7.9            </td>, <td>Topper's Grade</td>, <td>
                8.7            </td>, <td>Grade Scale</td>, <td>
                10            </td>, <td class="orange_title tdhor" colspan="2" id="sub_title">Experience and Publications</td>, <td>Journal Publications</td>, <td>
                0            </td>, <td>Conference Publications</td>, <td>
                0            </td>, <td>Industrial Experience</td>, <td>
                0 Years, 0 Months            </td>, <td>Research Experience</td>, <td>
                0 Years, 0 Months            </td>, <td>Internship Experience</td>, <td>
                0 Years, 0 Months            </td>, <td class="orange_title tdhor" colspan="2" id="sub_title">Visa Information</td>, <td>Undergraduate Arrears</td>, <td>
                0            </td>, <td>Home Country</td>, <td>
</td>, <td>Destination Country</td>, <td>
</td>, <td>Applied Visa Type</td>, <td>
                Still To Apply            </td>, <td class="orange_title tdhor" colspan="2" id="sub_title">Visa Decision</td>, <td>Visa Consulate City</td>, <td>
</td>, <td>Decision</td>, <td>
                Not Applied            </td>, <td>Appointment Date</td>, <td>
</td>, <td>Applied University</td>, <td>
</td>, <td>Type of Finance Docs</td>, <td>
                Not Applicable            </td>, <td class="orange_title tdhor" colspan="2" id="sub_title">Financial Aid</td>, <td>Type of Financial Aid</td>, <td>
                Not Applicable            </td>, <td>Amount</td>, <td>
                0            </td>, <td class="orange_title tdhor" colspan="2" id="sub_title">Other Miscellaneous Details</td>, <td align="" colspan="2">
<br/>c)2 decent academic projects.            </td>]
td
td Real Name
td franklin
td Edulix Nickname
td 1987frank
td Application Details
td Program
td MS
td Major
td Computer Science
td Specialization
td Artificial Intelligence,Algorithms,Programming Languages
td Term and Year
td Spring - 2014
td Standardized Test Scores
td
td GRE
td Quantitative:
td 170
td Verbal:
td 153
td AWA:
td 3.5
td GMAT
td Quantitative:
td
td Verbal:
td
td AWA:
td
td Integrated Reasoning:
td
td TOEFL
td Score:
td 105
td TWE (Essay):
td 29
td
td IELTS
td Score:
td
td Undergraduate Details
td University/College
td College Of Engineering, Trivandrum
td Department
td CSE
td Grade
td 7.9
td Topper's Grade
td 8.7
td Grade Scale
td 10
td Experience and Publications
td Journal Publications
td 0
td Conference Publications
td 0
td Industrial Experience
td 0 Years, 0 Months
td Research Experience
td 0 Years, 0 Months
td Internship Experience
td 0 Years, 0 Months
td Visa Information
td Undergraduate Arrears
td 0
td Home Country
td
td Destination Country
td
td Applied Visa Type
td Still To Apply
td Visa Decision
td Visa Consulate City
td
td Decision
td Not Applied
td Appointment Date
td
td Applied University
td
td Type of Finance Docs
td Not Applicable
td Financial Aid
td Type of Financial Aid
td Not Applicable
td Amount
td 0
td Other Miscellaneous Details
td

In [34]:
soup.find_all('td')

[<td align="center" class="orange_title tdhor" colspan="2" id="sub_title">
                 Details of
                 <a class="no_uline" href="" style="color:#d73117 !important;">1987frank</a> </td>,
 <td width="50%">Real Name</td>,
 <td width="50%">
                 franklin            </td>,
 <td>Edulix Nickname</td>,
 <td>
                 1987frank            </td>,
 <td class="orange_title tdhor" colspan="2" id="sub_title">Application Details</td>,
 <td>Program</td>,
 <td>
                 MS            </td>,
 <td>Major</td>,
 <td>
                 Computer Science            </td>,
 <td>Specialization</td>,
 <td>
                 Artificial Intelligence,Algorithms,Programming Languages            </td>,
 <td>Term and Year</td>,
 <td>
                 Spring - 2014            </td>,
 <td class="orange_title tdhor" colspan="2" id="sub_title">Standardized Test Scores</td>,
 <td class="tdbottom" colspan="2">
 <table border="0" width="100%">
 <tr>
 <td align="left">GRE</td>
 <td align="right">Quantitative:</td>
 <td>
                             170                        </td>
 <td align="right">Verbal:</td>
 <td>
                             153                        </td>
 <td align="right">AWA:</td>
 <td>
                             3.5                        </td>
 </tr>
 <tr>
 <td align="left">GMAT</td>
 <td align="right">Quantitative:</td>
 <td>
 </td>
 <td align="right">Verbal:</td>
 <td>
 </td>
 <td align="right">AWA:</td>
 <td>
 </td>
 <td align="right">Integrated Reasoning:</td>
 <td>
 </td>
 </tr>
 <tr>
 <td align="left">TOEFL</td>
 <td align="right">Score:</td>
 <td>
                             105                        </td>
 <td align="right">TWE (Essay):</td>
 <td>
                             29                        </td>
 <td colspan="2"> </td>
 </tr>
 <tr>
 <td align="left">IELTS</td>
 <td align="right">Score:</td>
 <td>
 </td>
 </tr>
 </table>
 </td>,
 <td align="left">GRE</td>,
 <td align="right">Quantitative:</td>,
 <td>
                             170                        </td>,
 <td align="right">Verbal:</td>,
 <td>
                             153                        </td>,
 <td align="right">AWA:</td>,
 <td>
                             3.5                        </td>,
 <td align="left">GMAT</td>,
 <td align="right">Quantitative:</td>,
 <td>
 </td>,
 <td align="right">Verbal:</td>,
 <td>
 </td>,
 <td align="right">AWA:</td>,
 <td>
 </td>,
 <td align="right">Integrated Reasoning:</td>,
 <td>
 </td>,
 <td align="left">TOEFL</td>,
 <td align="right">Score:</td>,
 <td>
                             105                        </td>,
 <td align="right">TWE (Essay):</td>,
 <td>
                             29                        </td>,
 <td colspan="2"> </td>,
 <td align="left">IELTS</td>,
 <td align="right">Score:</td>,
 <td>
 </td>,
 <td class="orange_title tdhor" colspan="2" id="sub_title">Undergraduate Details</td>,
 <td>University/College</td>,
 <td>
                 College Of Engineering, Trivandrum            </td>,
 <td>Department</td>,
 <td>
                 CSE            </td>,
 <td>Grade</td>,
 <td>
                 7.9            </td>,
 <td>Topper's Grade</td>,
 <td>
                 8.7            </td>,
 <td>Grade Scale</td>,
 <td>
                 10            </td>,
 <td class="orange_title tdhor" colspan="2" id="sub_title">Experience and Publications</td>,
 <td>Journal Publications</td>,
 <td>
                 0            </td>,
 <td>Conference Publications</td>,
 <td>
                 0            </td>,
 <td>Industrial Experience</td>,
 <td>
                 0 Years, 0 Months            </td>,
 <td>Research Experience</td>,
 <td>
                 0 Years, 0 Months            </td>,
 <td>Internship Experience</td>,
 <td>
                 0 Years, 0 Months            </td>,
 <td class="orange_title tdhor" colspan="2" id="sub_title">Visa Information</td>,
 <td>Undergraduate Arrears</td>,
 <td>
                 0            </td>,
 <td>Home Country</td>,
 <td>
 </td>,
 <td>Destination Country</td>,
 <td>
 </td>,
 <td>Applied Visa Type</td>,
 <td>
                 Still To Apply            </td>,
 <td class="orange_title tdhor" colspan="2" id="sub_title">Visa Decision</td>,
 <td>Visa Consulate City</td>,
 <td>
 </td>,
 <td>Decision</td>,
 <td>
                 Not Applied            </td>,
 <td>Appointment Date</td>,
 <td>
 </td>,
 <td>Applied University</td>,
 <td>
 </td>,
 <td>Type of Finance Docs</td>,
 <td>
                 Not Applicable            </td>,
 <td class="orange_title tdhor" colspan="2" id="sub_title">Financial Aid</td>,
 <td>Type of Financial Aid</td>,
 <td>
                 Not Applicable            </td>,
 <td>Amount</td>,
 <td>
                 0            </td>,
 <td class="orange_title tdhor" colspan="2" id="sub_title">Other Miscellaneous Details</td>,
 <td align="" colspan="2">
                 a)Work experience- 3yrs at Applied Materials-Automation software development.
 <br/>b)No research papers :(
 <br/>c)2 decent academic projects.            </td>,
 <td align="center" class="orange_title tdbottom" colspan="2" id="sub_title">
                     Universities Applied
                 </td>,
 <td class="tdtop"><a class="hov_line" href="univreview.php?univid=293">Iowa State University</a></td>,
 <td class="tdtop"><span>Result not available</span></td>,
 <td class="tdtop"><a class="hov_line" href="univreview.php?univid=1471">Rutgers University New Brunswick/Piscataway</a></td>,
 <td class="tdtop"><span>Result not available</span></td>,
 <td class="tdtop"><a class="hov_line" href="univreview.php?univid=1586">SUNY Stony Brook</a></td>,
 <td class="tdtop"><span>Result not available</span></td>,
 <td class="tdtop"><a class="hov_line" href="univreview.php?univid=969">Arizona State University</a></td>,
 <td class="tdtop"><span class="yes">Admit</span></td>,
 <td colspan="2" style="padding-left:40px">first admit..</td>,
 <td class="tdtop"><a class="hov_line" href="univreview.php?univid=1127">University of Florida</a></td>,
 <td class="tdtop"><span class="yes">Admit</span></td>,
 <td class="tdtop"><a class="hov_line" href="univreview.php?univid=1220">University of Illinois Chicago</a></td>,
 <td class="tdtop"><span class="no">Reject</span></td>]

In [37]:
for string in soup.table.strings:
    print string

                Details of

1987frank







Real Name



                franklin






Edulix Nickname



                1987frank






Application Details






Program



                MS






Major



                Computer Science






Specialization



                Artificial Intelligence,Algorithms,Programming Languages






Term and Year



                Spring - 2014






Standardized Test Scores












GRE


Quantitative:



                            170


Verbal:



                            153


AWA:



                            3.5






GMAT


Quantitative:






Verbal:






AWA:






Integrated Reasoning:










TOEFL


Score:



                            105


TWE (Essay):



                            29









IELTS


Score:
















Undergraduate Details






University/College



                College Of Engineering, Trivandrum






Department



                CSE






Grade



                7.9






Topper's Grade



                8.7






Grade Scale



                10








Experience and Publications






Journal Publications



                0






Conference Publications



                0






Industrial Experience



                0 Years, 0 Months






Research Experience



                0 Years, 0 Months






Internship Experience



                0 Years, 0 Months






Visa Information






Undergraduate Arrears



                0






Home Country










Destination Country










Applied Visa Type



                Still To Apply






Visa Decision






Visa Consulate City










Decision



                Not Applied






Appointment Date










Applied University










Type of Finance Docs



                Not Applicable






Financial Aid






Type of Financial Aid



                Not Applicable






Amount



                0








Other Miscellaneous Details







                a)Work experience- 3yrs at Applied Materials-Automation software development.
b)No research papers :(
c)2 decent academic projects.